dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
platforms:
  - name: clickhouse
    image: docker.io/vadimchikpank/docker-debian-bookworm-ansible:latest
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
    pre_build_image: true
driver:
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: podman

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../"

verifier:
  name: ansible
  # journalctl -u clickhouse-server.service